service: sls-weport-test
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20210705

functions:
  hello:
    handler: src/apis/sample.hello
    environment:
      WEPORT_PG_URI: ${env:WEPORT_PG_URI}
      SERVERLESS_AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SERVERLESS_AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

    events:
      - schedule: rate(2 hours) #CloudWatch
      - http:  #API GATEWAY
          method: post
          path: hello
          integration: lambda

  goodbye:
    handler: src/apis/sample2.goodbye
    events:
      - http:
          method: get
          path: goodbye
          integration: lambda
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
