service: sls-test
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: ${file(./config.${self:provider.stage}.json):REGION}
  lambdaHashingVersion: 20210705

functions:
  hello:
    handler: src/apis/sample.hello
    environment:
      COMMON_CDN_S3_BUCKET: ${file(./config.${self:provider.stage}.json):COMMON_CDN_S3_BUCKET}
      PG_URI:  ${file(./config.${self:provider.stage}.json):PG_URI}
      SERVERLESS_AWS_ACCESS_KEY_ID:  ${file(./config.${self:provider.stage}.json):SERVERLESS_AWS_ACCESS_KEY_ID}
      SERVERLESS_AWS_SECRET_ACCESS_KEY:  ${file(./config.${self:provider.stage}.json):SERVERLESS_AWS_SECRET_ACCESS_KEY}

    events:
      - schedule: rate(2 hours) #CloudWatch
      - http:  #API GATEWAY
          method: post
          path: hello
          integration: lambda

  goodbye:
    handler: src/apis/sample2.goodbye
    events:
      - http:
          method: get
          path: goodbye
          integration: lambda
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
        - pg-hstore
